using System.Reflection;
using Microsoft.AspNetCore.Components;
using Controls = ArkheideSystem.Flourish.Blazor.Components;

namespace ArkheideSystem.Gallery.Flourish.Blazor.Models;

internal static class ParameterMeaning
{
    public static string DescriptionKey(PropertyInfo parameter) => parameter.Name switch
    {
        "Compact" when parameter.DeclaringType == typeof(Controls.NavigationChoices) => "Key.Parameter_Compact_NavigationChoices",
        "StackTitleWords" => "Key.Parameter_StackTitleWords",
        "SideContent" when parameter.DeclaringType == typeof(Controls.PresentationHero) => "Key.Parameter_SideContent_PresentationHero",
        "Tone" when parameter.DeclaringType == typeof(Controls.AccessFormSurface) => "Key.Parameter_Tone_AccessFormSurface",
        "TriggerVariant" => "Key.Parameter_TriggerVariant",
        "Icon" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_Icon_MultiSelectBox",
        "Icon" when parameter.DeclaringType == typeof(Controls.ActionMenu) => "Key.Parameter_Icon_ActionMenu",
        "PrimaryDisabled" when parameter.DeclaringType == typeof(Controls.SplitButton) => "Key.Parameter_PrimaryDisabled_SplitButton",
        "Items" when parameter.DeclaringType == typeof(Controls.NavigationChoices) => "Key.Parameter_Items_NavigationChoices",
        "ActiveKey" when parameter.DeclaringType == typeof(Controls.NavigationChoices) => "Key.Parameter_ActiveKey_NavigationChoices",
        "ChildContent" when parameter.DeclaringType == typeof(Controls.NavigationChoices) => "Key.Parameter_ChildContent_NavigationChoices",
        "For" when parameter.DeclaringType == typeof(Controls.ValidationMessages) => "Key.Parameter_For_ValidationMessages",
        "Error" when parameter.DeclaringType == typeof(Controls.ValidationMessages) => "Key.Parameter_Error_ValidationMessages",
        "Items" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_Items_MultiSelectBox",
        "Changed" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_Changed_MultiSelectBox",
        "MinimumSelected" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_MinimumSelected_MultiSelectBox",
        "MaximumSelections" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_MaximumSelections_MultiSelectBox",
        "CanReorder" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_CanReorder_MultiSelectBox",
        "Searchable" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_Searchable_MultiSelectBox",
        "CreateRequested" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_CreateRequested_MultiSelectBox",
        "NewItemMaximumLength" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_NewItemMaximumLength_MultiSelectBox",
        "Label" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_Label_MultiSelectBox",
        "LabelledBy" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_LabelledBy_MultiSelectBox",
        "Static" when parameter.DeclaringType == typeof(Controls.MultiSelectBox) => "Key.Parameter_Static_MultiSelectBox",
        "ShowDisplayOptions" => "Key.Parameter_ShowDisplayOptions",
        "IncludeAllColumns" => "Key.Parameter_IncludeAllColumns",
        "Value" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "Key.Parameter_Value_DataSearch",
        "ColumnKey" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "Key.Parameter_ColumnKey_DataSearch",
        "Changed" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "Key.Parameter_Changed_DataSearch",
        "Columns" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "Key.Parameter_Columns_DataSearch",
        "MaximumLength" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "Key.Parameter_MaximumLength_DataSearch",
        "Text" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "Key.Parameter_Text_DataSearch",
        "ChildContent" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "Key.Parameter_ChildContent_DataSearch",
        "Threshold" when parameter.DeclaringType == typeof(Controls.BackToTop) => "Key.Parameter_Threshold_BackToTop",
        "IndependentScales" => "Key.Parameter_IndependentScales",
        "ShowLegend" => "Key.Parameter_ShowLegend",
        "MaximumLabel" => "Key.Parameter_MaximumLabel",
        "PointCaption" => "Key.Parameter_PointCaption",
        "Labels" when parameter.DeclaringType == typeof(Controls.LineChart) => "Key.Parameter_Labels_LineChart",
        "ControlsContent" when parameter.DeclaringType == typeof(Controls.LineChart) => "Key.Parameter_ControlsContent_LineChart",
        "Heading" when parameter.DeclaringType == typeof(Controls.LineChart) => "Key.Parameter_Heading_LineChart",
        "Series" when parameter.DeclaringType == typeof(Controls.LineChart) => "Key.Parameter_Series_LineChart",
        "Value" when parameter.DeclaringType == typeof(Controls.CopyText) => "Key.Parameter_Value_CopyText",
        "Value" when IsGenericControl(parameter, typeof(Controls.Primitives.ReferenceDropdown<>)) => "Key.Parameter_Value_Primitives_ReferenceDropdown",
        "Value" => "Key.Parameter_Value",
        "ValueChanged" when IsGenericControl(parameter, typeof(Controls.Primitives.ReferenceDropdown<>)) => "Key.Parameter_ValueChanged_Primitives_ReferenceDropdown",
        "ValueChanged" => "Key.Parameter_ValueChanged",
        "ValueExpression" => "Key.Parameter_ValueExpression",
        "DisplayName" => "Key.Parameter_DisplayName",
        "MessageFormatter" => "Key.Parameter_MessageFormatter",
        "ParsingErrorMessage" => "Key.Parameter_ParsingErrorMessage",
        "OnClick" => "Key.Parameter_OnClick",
        "OpenOnHover" => "Key.Parameter_OpenOnHover",
        "Actions" => typeof(RenderFragment).IsAssignableFrom(parameter.PropertyType)
            || parameter.PropertyType.IsGenericType && parameter.PropertyType.GetGenericTypeDefinition() == typeof(RenderFragment<>)
            ? "Key.Parameter_Actions_Content" : "Key.Parameter_Actions_Collection",
        "ChildContent" when parameter.DeclaringType == typeof(Controls.ActionMenu) => "Key.Parameter_ChildContent_ActionMenu",
        "ChildContent" => "Key.Parameter_ChildContent",
        "Brand" => "Key.Parameter_Brand",
        "Footer" => "Key.Parameter_Footer",
        "DocumentFlow" => "Key.Parameter_DocumentFlow",
        "Tone" => "Key.Parameter_Tone",
        "MinHeight" => "Key.Parameter_MinHeight",
        "FullHeight" => "Key.Parameter_FullHeight",
        "ProjectName" => "Key.Parameter_ProjectName",
        "LogoAlternativeText" => "Key.Parameter_LogoAlternativeText",
        "MenuContent" => "Key.Parameter_MenuContent",
        "Width" when parameter.DeclaringType == typeof(Controls.SplitButton) => "Key.Parameter_Width_SplitButton",
        "TriggerClass" => "Key.Parameter_TriggerClass",
        "TriggerAttributes" => "Key.Parameter_TriggerAttributes",
        "TitleId" => "Key.Parameter_TitleId",
        "HeadingLevel" => "Key.Parameter_HeadingLevel",
        "Copyright" => "Key.Parameter_Copyright",
        "Wide" => "Key.Parameter_Wide",
        "LinkScopeId" => "Key.Parameter_LinkScopeId",
        "AutoRotate" => "Key.Parameter_AutoRotate",
        "RotationControlIconOnly" => "Key.Parameter_RotationControlIconOnly",
        "RotationIntervalMilliseconds" => "Key.Parameter_RotationIntervalMilliseconds",
        "PauseRotationLabel" => "Key.Parameter_PauseRotationLabel",
        "ResumeRotationLabel" => "Key.Parameter_ResumeRotationLabel",
        "AdditionalAttributes" => "Key.Parameter_AdditionalAttributes",
        "Class" or "TableClass" or "ContentClass" => "Key.Parameter_Class",
        "Style" => "Key.Parameter_Style",
        "Name" or "Icon" => "Key.Parameter_Name",
        "Dotted" when parameter.DeclaringType == typeof(Controls.PresentationBand) || parameter.DeclaringType == typeof(Controls.PresentationHero)
            => "Key.Parameter_Dotted_PresentationBanner",
        "Dotted" => "Key.Parameter_Dotted",
        "Centered" when parameter.DeclaringType == typeof(Controls.UniformGrid)
            => "Key.Parameter_Centered_UniformGrid",
        "Centered" => "Key.Parameter_Centered",
        "CopyText" => "Key.Parameter_CopyText",
        "OwnsDocument" => "Key.Parameter_OwnsDocument",
        "Shape" => "Key.Parameter_Shape",
        "MaxCellSize" => "Key.Parameter_MaxCellSize",
        "MaxCellHeight" => "Key.Parameter_MaxCellHeight",
        "IconSupport" => "Key.Parameter_IconSupport",
        "Variant" when (Nullable.GetUnderlyingType(parameter.PropertyType) ?? parameter.PropertyType) == typeof(Controls.UniformGridVariant)
            => parameter.PropertyType == typeof(Controls.UniformGridVariant)
                ? "Key.Parameter_Variant_UniformGrid"
                : "Key.Parameter_Variant_UniformGridOptional",
        "Variant" => "Key.Parameter_Variant",
        "OnSecondaryClick" => "Key.Parameter_OnSecondaryClick",
        "Selected" => "Key.Parameter_Selected",
        "Expanded" => "Key.Parameter_Expanded",
        "SecondaryControls" => "Key.Parameter_SecondaryControls",
        "SecondaryIcon" => "Key.Parameter_SecondaryIcon",
        "PrimaryAttributes" or "SecondaryAttributes" => "Key.Parameter_PrimaryAttributes",
        "PrimaryClass" or "SecondaryClass" => "Key.Parameter_PrimaryClass",
        "Type" when parameter.DeclaringType?.IsGenericType == true && parameter.DeclaringType.GetGenericTypeDefinition() == typeof(Controls.DateBox<>)
            => "Key.Parameter_Type_DateBox",
        "Type" => "Key.Parameter_Type",
        "Busy" or "EditingBusy" => "Key.Parameter_Busy",
        "Disabled" => "Key.Parameter_Disabled",
        "DisabledMessage" => "Key.Parameter_DisabledMessage",
        "Hidden" => "Key.Parameter_Hidden",
        "Title" when parameter.DeclaringType == typeof(Controls.UniformGridItem) || parameter.DeclaringType == typeof(Controls.UniformGridButton)
            => "Key.Parameter_Title_UniformGridCell",
        "Text" when parameter.DeclaringType == typeof(Controls.UniformGridItem) || parameter.DeclaringType == typeof(Controls.UniformGridButton)
            => "Key.Parameter_Text_UniformGridCell",
        "Label" or "Title" or "Message" or "Description" or "Text" => "Key.Parameter_Label",
        "Placeholder" => "Key.Parameter_Placeholder",
        "Id" or "ContentId" => "Key.Parameter_Id",
        "LabelledBy" => "Key.Parameter_LabelledBy",
        "For" => "Key.Parameter_For",
        "Required" => "Key.Parameter_Required",
        "Error" => "Key.Parameter_Error",
        "FullWidth" => "Key.Parameter_FullWidth",
        "Columns" when parameter.PropertyType == typeof(bool) => "Key.Parameter_Columns_bool",
        "Columns" when parameter.PropertyType == typeof(int) => "Key.Parameter_Columns_int",
        "Columns" when parameter.PropertyType == typeof(int?) => "Key.Parameter_Columns_intNullable",
        "Columns" when IsListView(parameter) => "Key.Parameter_Columns_ListView",
        "Columns" => "Key.Parameter_Columns",
        "NarrowColumns" when parameter.DeclaringType == typeof(Controls.UniformGrid)
            => "Key.Parameter_NarrowColumns_UniformGrid",
        "NarrowColumns" => "Key.Parameter_NarrowColumns",
        "Fluid" => "Key.Parameter_Fluid",
        "Compact" => "Key.Parameter_Compact",
        "FocusInvalidFields" => "Key.Parameter_FocusInvalidFields",
        "Min" or "Max" or "Step" => "Key.Parameter_Min",
        "MaxLength" or "MaximumLength" or "NewItemMaximumLength" => "Key.Parameter_MaxLength",
        "Multiline" => "Key.Parameter_Multiline",
        "Rows" when parameter.PropertyType == typeof(int) => "Key.Parameter_Rows_int",
        "Rows" when parameter.PropertyType == typeof(int?) => "Key.Parameter_Rows_intNullable",
        "Rows" => "Key.Parameter_Rows",
        "Mask" => "Key.Parameter_Mask",
        "InputMode" => "Key.Parameter_InputMode",
        "Options" => "Key.Parameter_Options",
        "Items" when IsListView(parameter) => "Key.Parameter_Items_ListView",
        "Items" => "Key.Parameter_Items",
        "ItemKey" when IsListView(parameter) => "Key.Parameter_ItemKey_ListView",
        "ValueSelector" or "KeySelector" or "ItemKey" => "Key.Parameter_ValueSelector",
        "TextSelector" or "SearchTextSelector" => "Key.Parameter_TextSelector",
        "SelectedValues" => "Key.Parameter_SelectedValues",
        "SelectionChanged" => "Key.Parameter_SelectionChanged",
        "ItemSelected" => "Key.Parameter_ItemSelected",
        "AllowNone" => "Key.Parameter_AllowNone",
        "CreateRequested" => "Key.Parameter_CreateRequested",
        "MaximumSelections" or "MaximumResults" => "Key.Parameter_MaximumResultsLimit",
        "FilterItems" when parameter.PropertyType == typeof(bool) => "Key.Parameter_FilterItems_bool",
        "FilterItems" => "Key.Parameter_FilterItems",
        "DebounceMilliseconds" => "Key.Parameter_DebounceMilliseconds",
        "SearchRequested" => "Key.Parameter_SearchRequested",
        "SearchChanged" when IsGenericControl(parameter, typeof(Controls.DataTable<>)) => "Key.Parameter_SearchChanged_DataTable",
        "SearchChanged" or "InputChanged" or "Changed" => "Key.Parameter_SearchChanged",
        "SearchCleared" => "Key.Parameter_SearchCleared",
        "OnSearch" => "Key.Parameter_OnSearch",
        "ColumnKey" => "Key.Parameter_ColumnKey",
        "Searchable" => "Key.Parameter_Searchable",
        "View" when parameter.DeclaringType == typeof(Controls.Dialog) => "Key.Parameter_View_Dialog",
        "View" => "Key.Parameter_View",
        "ViewChanged" => "Key.Parameter_ViewChanged",
        "Loading" => "Key.Parameter_Loading",
        "LoadingMessage" or "EmptyMessage" or "EmptyText" or "EmptySelectionText" or "MultipleSelectionText" or "UnlistedName" => "Key.Parameter_LoadingMessage",
        "PageSize" => "Key.Parameter_PageSize",
        "PageSizeChanged" => "Key.Parameter_PageSizeChanged",
        "CurrentPage" => "Key.Parameter_CurrentPage",
        "TotalCount" => "Key.Parameter_TotalCount",
        "PageChanged" => "Key.Parameter_PageChanged",
        "IsLimited" or "HasMore" => "Key.Parameter_IsLimited",
        "ShowRange" => "Key.Parameter_ShowRange",
        "PaginationResetKey" => "Key.Parameter_PaginationResetKey",
        "Culture" when IsListView(parameter) => "Key.Parameter_Culture_ListView",
        "Culture" => "Key.Parameter_Culture",
        "OnRowOpen" => "Key.Parameter_OnRowOpen",
        "RowOpenAvailable" => "Key.Parameter_RowOpenAvailable",
        "RowActionsContent" => "Key.Parameter_RowActionsContent",
        "RowHeaderKey" => "Key.Parameter_RowHeaderKey",
        "Caption" when IsListView(parameter) => "Key.Parameter_Caption_ListView",
        "CellTemplate" when IsListView(parameter) => "Key.Parameter_CellTemplate_ListView",
        "CellTemplate" when parameter.DeclaringType == typeof(Controls.Primitives.EditingGrid) => "Key.Parameter_CellTemplate_EditingGrid",
        "CellTemplate" or "BulkEditCell" => "Key.Parameter_CellTemplate",
        "Progressive" => "Key.Parameter_Progressive",
        "NativeRowOpen" => "Key.Parameter_NativeRowOpen",
        "RowOpenHref" => "Key.Parameter_RowOpenHref",
        "SearchMode" => "Key.Parameter_SearchMode",
        "SearchQuery" or "SearchColumnKey" => "Key.Parameter_SearchQuery",
        "SearchContent" => "Key.Parameter_SearchContent",
        "SearchDisabled" => "Key.Parameter_SearchDisabled",
        "SearchId" => "Key.Parameter_SearchId",
        "SearchMaximumLength" => "Key.Parameter_SearchMaximumLength",
        "ShowRowActions" => "Key.Parameter_ShowRowActions",
        "PreferenceKey" when IsGenericControl(parameter, typeof(Controls.DataTable<>)) => "Key.Parameter_PreferenceKey_DataTable",
        "PreferenceKey" => "Key.Parameter_PreferenceKey",
        "Purpose" => "Key.Parameter_Purpose",
        "CellChanged" => "Key.Parameter_CellChanged",
        "Interactions" => "Key.Parameter_Interactions",
        "MeasurementRevision" => "Key.Parameter_MeasurementRevision",
        "EditDisabled" => "Key.Parameter_EditDisabled",
        "BulkEditing" => "Key.Parameter_BulkEditing",
        "BulkEditRequested" => "Key.Parameter_BulkEditRequested",
        "IsSelectedForEditing" or "AllEditSelected" => "Key.Parameter_IsSelectedForEditing",
        "ToggleEditSelection" or "ToggleAllEditSelection" => "Key.Parameter_ToggleEditSelection",
        "SpreadsheetEditHref" => "Key.Parameter_SpreadsheetEditHref",
        "BrowserControlled" => "Key.Parameter_BrowserControlled",
        "Dismissible" => "Key.Parameter_Dismissible",
        "Views" => "Key.Parameter_Views",
        "IsOpen" => "Key.Parameter_IsOpen",
        "IsOpenChanged" => "Key.Parameter_IsOpenChanged",
        "CanClose" => "Key.Parameter_CanClose",
        "Presentation" => "Key.Parameter_Presentation",
        "TriggerContent" => "Key.Parameter_TriggerContent",
        "Severity" => "Key.Parameter_Severity",
        "Subtle" => "Key.Parameter_Subtle",
        "Announce" => "Key.Parameter_Announce",
        "Role" => "Key.Parameter_Role",
        "StatusText" => "Key.Parameter_StatusText",
        "Stopped" => "Key.Parameter_Stopped",
        "InitiallyOpen" => "Key.Parameter_InitiallyOpen",
        "Href" or "HomeHref" or "ParentHref" or "IdentityHref" => "Key.Parameter_Href",
        "ParentLabel" => "Key.Parameter_ParentLabel",
        "IdentityName" or "BrandName" or "ApplicationTitle" => "Key.Parameter_IdentityName",
        "LogoPath" => "Key.Parameter_LogoPath",
        "Match" => "Key.Parameter_Match",
        "IsCurrent" => "Key.Parameter_IsCurrent",
        "PrimaryNavigation" or "SecondaryNavigation" => "Key.Parameter_PrimaryNavigation",
        "ShowSecondary" => "Key.Parameter_ShowSecondary",
        "DocumentKey" => "Key.Parameter_DocumentKey",
        "SideContent" => "Key.Parameter_SideContent",
        "Form" => "Key.Parameter_Form",
        "HasUnsavedChanges" => "Key.Parameter_HasUnsavedChanges",
        "Locked" => "Key.Parameter_Locked",
        "Emphasized" => "Key.Parameter_Emphasized",
        "Prominent" => "Key.Parameter_Prominent",
        "Stacked" => "Key.Parameter_Stacked",
        "Language" => "Key.Parameter_Language",
        "Status" or "TitleBar" or "TitleBarStart" or "TitleBarBrand" or "TitleBarEnd" or "LeadingActions" or "EndActions" or "Services" => "Key.Parameter_Status",
        _ when parameter.Name.EndsWith("Label", StringComparison.Ordinal) => "Key.Parameter_AccessibleLabel",
        _ when typeof(RenderFragment).IsAssignableFrom(parameter.PropertyType) => "Key.Parameter_Content",
        _ => "Key.Parameter_HostConfiguration"
    };

    private static bool IsListView(PropertyInfo parameter) => parameter.DeclaringType?.IsGenericType == true
        && parameter.DeclaringType.GetGenericTypeDefinition() == typeof(Controls.ListView<>);
    private static bool IsGenericControl(PropertyInfo parameter, Type definition) => parameter.DeclaringType?.IsGenericType == true
        && parameter.DeclaringType.GetGenericTypeDefinition() == definition;
}
