using System.Reflection;
using Microsoft.AspNetCore.Components;
using Controls = ArkheideSystem.Flourish.Blazor.Components;

namespace ArkheideSystem.Gallery.Flourish.Blazor.Models;

internal static class ParameterMeaning
{
    public static string Describe(PropertyInfo parameter) => parameter.Name switch
    {
        "IncludeAllColumns" => "搜索增加全部列选项；空列键代表全部可搜索列。默认 false 选择第一个 Searchable 列，DataTable 本地搜索显式开启。",
        "Value" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "宿主提供的受控查询文字；Changed 返回新请求，不自行过滤或持久化结果。",
        "ColumnKey" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "当前可搜索 TableColumn 的稳定键；无效键退回首列或显式开启的全部列，不能选取 Searchable=false 列。",
        "Changed" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "通知一个 TableSearchRequest(ColumnKey, Value)；全部列用 null。宿主决定是否接受并更新受控参数，禁用或无搜索列时不发回调。",
        "Columns" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "共享 TableColumn<TItem>，仅列出 Searchable=true 的列；所有键必须非空且不重复。",
        "MaximumLength" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "必须为正数，默认 200；设置原生 maxlength 并限制输入回调长度，不修改宿主已提供的查询值。",
        "Text" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "共享 TableText 的 SearchBy / AllColumns / SearchContent 显式文字；省略时使用作用域本地化。",
        "ChildContent" when IsGenericControl(parameter, typeof(Controls.DataSearch<>)) => "与搜索字段同行的附加筛选控件；库不重绘插槽内复选框或其他输入的皮肤，业务筛选仍由宿主负责。",
        "Threshold" when parameter.DeclaringType == typeof(Controls.BackToTop) => "指定正文滚动超过此像素值时显示增强按钮；静态 SSR 保留真实片段链接，不移走其他滚动区。",
        "IndependentScales" => "折线序列显式采用独立刻度；每条序列的最大值展示在图例中，不将不同量纲误当相同数值。",
        "ShowLegend" => "显示序列名称及刻度说明；精确数据仍保留于可访问表格中。",
        "MaximumLabel" => "折线图最大值说明的本地化文字。",
        "PointCaption" => "精确值表格中标签列的名称。",
        "Labels" when parameter.DeclaringType == typeof(Controls.LineChart) => "稳定且不重复的标签与可选提示；数量必须与每条序列的值一致。",
        "Series" when parameter.DeclaringType == typeof(Controls.LineChart) => "具有稳定键、名称、十进制值、格式函数、可选最大值与可见性的序列；库负责几何、编码及主题，宿主负责原始业务值。",
        "Value" => "当前值；输入与切换控件配合 ValueChanged 使用 @bind-Value，进度使用 0–100 或 null。",
        "ValueChanged" => "值变化通知；@bind-Value 自动更新宿主值。",
        "ValueExpression" => "绑定的模型字段表达式，供 EditContext 验证与字段标识使用。",
        "DisplayName" => "解析或验证消息使用的字段名称。",
        "ParsingErrorMessage" => "输入无法解析为目标类型时的错误消息。",
        "OnClick" => "按钮激活回调；可返回异步任务。",
        "OpenOnHover" => "Actions 数据驱动模式：鼠标进入触发区域时打开菜单且不抢焦点，离开触发区和弹窗后关闭；键盘和触屏仍可激活。顶部栏菜单自动启用。与原生 ChildContent 不可同时使用；原生模式采用 details 点击/键盘开口。",
        "Actions" => typeof(RenderFragment).IsAssignableFrom(parameter.PropertyType)
            || parameter.PropertyType.IsGenericType && parameter.PropertyType.GetGenericTypeDefinition() == typeof(RenderFragment<>)
            ? "标题或操作区的 Razor 内容插槽。" : "操作集合与回调，可包含禁用或危险标记。",
        "ChildContent" when parameter.DeclaringType == typeof(Controls.ActionMenu) => "同一标准菜单控制器中的原生动作内容；与非空 Actions 及 OpenOnHover 互斥。SSR 保留 details 开口且不设 popover，浏览器就绪后复用 attachDisclosureMenu。宿主提供 role=menuitem、标准菜单类及真实 GET/POST 属性；Disabled 统一 inert，模板的 Busy/重复提交锁和业务授权仍由宿主/服务器负责。",
        "ChildContent" => "控件内部的 Razor 内容；业务数据由宿主提供。",
        "Brand" => "访问面板的品牌与入口说明插槽，不生成认证行为。",
        "Footer" => "正文后面的标准页脚插槽，适用于展示页面的文档流组合。",
        "DocumentFlow" => "使用文档滚动与自然高度，适用于展示类宿主；false 保留业务壳单一正文滚动轨道。",
        "Tone" => "展示横幅背景颜色角色：Canvas、Surface 或 Primary；内部内容仍使用居中限宽轨道。推荐相邻横幅交替不同角色，而非自动按 DOM 次序换色。",
        "MinHeight" => "横幅最小高度，单位 px，默认 450；必须非负，0 为自然内容高度。长文、窄屏或缩放时允许增高，不裁切控件。",
        "FullHeight" => "整页横幅模式，最小高度取动态视口 100dvh 和 MinHeight 的较大值；内容可自然增长，默认关闭。",
        "Banner" => "独立访问页使用共享整页横幅，背景全宽、内容限宽；不生成第二个 main，默认关闭以兼容原访问页。",
        "ProjectName" => "实例项目艺术字覆盖；省略时读取 ConfigureProject 的 literal 或作用域本地化名称。",
        "LogoAlternativeText" => "图片替代文字；省略时读取已配置项目标志描述，空文字避免与可读项目名重复。",
        "MenuContent" => "原生下拉内容插槽，静态 SSR 和键盘可用；放标准导航/动作，不拥有认证。与宿主 Expanded 或 OnSecondaryClick 互斥。",
        "Width" when parameter.DeclaringType == typeof(Controls.SplitButton) => "SplitButton 总宽度，单位 px，必须为正数；主体弹性填充，次按钮保持 48px 方形。FullWidth 优先。",
        "TriggerClass" => "追加到原生下拉 summary 触发器的 CSS 类。",
        "TriggerAttributes" => "原生 summary 触发器属性；不得伪造与 details 实际状态矛盾的展开状态。",
        "TitleId" => "标题稳定 HTML 标识，用于章节或面板的可访问关联。",
        "HeadingLevel" => "语义标题级别 1–6；Band 默认 2、LogoDisplayer 默认 1；不改变布局和艺术/正文场景。",
        "Watermark" => "显式覆盖页脚装饰背景字的兼容参数；省略时与标题一起跟随已配置项目名，不替代可读品牌与版权。",
        "Copyright" => "宿主提供的版权或展示声明。",
        "Wide" => "使用访问面板的宽布局变种，不改变表单协议与验证。",
        "LinkScopeId" => "当前报价链接区域的稳定 ID，限制锚点交互只影响本报价舞台。",
        "AutoRotate" => "启用展示报价渐进轮播及库内暂停/恢复按钮；减少动态效果或焦点/指针交互时暂停。false 不显示轮播控制。",
        "RotationControlIconOnly" => "仅将轮播控制改为标准 48px 图标按钮；默认 false 保留文字模式。aria-label 与 data-tooltip 沿用暂停/恢复标签及其本地化，SSR 未增强时仍禁用，不改变轮播逻辑。",
        "RotationIntervalMilliseconds" => "报价自动轮播间隔，单位毫秒；不执行价格或许可计算。",
        "PauseRotationLabel" => "暂停自动轮播按钮的文字；默认跟随框架作用域本地化，显式值优先，不改变报价内容或动作。",
        "ResumeRotationLabel" => "用户暂停后恢复自动轮播按钮的文字；默认跟随框架作用域本地化，显式值优先。",
        "AdditionalAttributes" => "未匹配的原生 HTML 属性，例如 id、aria-label 和 data-*。",
        "Class" or "CssClass" or "TableClass" or "ContentClass" => "追加到目标区域的 CSS 类。",
        "Style" => "目标区域的内联 CSS 或自定义属性。",
        "Name" or "Icon" => "Google 官方图标名称或兼容别名。",
        "Size" => "图标尺寸角色：standard、primary、tool、search 或 information。",
        "Dotted" when parameter.DeclaringType == typeof(Controls.PresentationBand) || parameter.DeclaringType == typeof(Controls.PresentationHero) || parameter.DeclaringType == typeof(Controls.Primitives.AccessSurface)
            => "横幅点阵装饰，默认 false；显式开启时使用相同标准点阵和当前颜色角色，与高度、正文和动作独立。",
        "Dotted" => "显示点阵背景；默认 true。与内容和复制功能独立。",
        "Centered" when parameter.DeclaringType == typeof(Controls.UniformGrid)
            => "将实际网格宽度在可用区域内水平居中；默认 false 保持起始对齐，不改变单元格尺寸、内容对齐或列数。仅在外层 UniformGrid 上配置。",
        "Centered" => "将背景板普通子内容居中；false 时靠左上。CodeBlock 始终从左上开始。",
        "CopyText" => "完整复制内容；null 隐藏复制动作。使用 CodeBlock 等子内容显示文本。",
        "OwnsDocument" => "默认 ApplicationLayout 独占视口并禁用文档滚动；嵌入式示例设为 false。",
        "Shape" => "在 UniformGrid 容器上设置单元格形状：默认 Rectangle，Square 为正方形；同时作用于 UniformGridItem 和 UniformGridButton，不改变整个容器的形状。",
        "MaxCellSize" => "正方形单元格的最大边长，默认 280px；长方形不受该限制。必须为正数。",
        "MaxCellHeight" => "长方形单元格的最大高度，默认 260px；不影响正方形。必须为正数，在外层 UniformGrid 上配置。",
        "IconSupport" => "null 时有 Icon 自动启用上下等分布局；true 将图标置于上半区中央，文案置于下半区中央；false 保留连续布局。单格配置优先于 UniformGrid 配置。",
        "Variant" when (Nullable.GetUnderlyingType(parameter.PropertyType) ?? parameter.PropertyType) == typeof(Controls.UniformGridVariant)
            => parameter.PropertyType == typeof(Controls.UniformGridVariant)
                ? "Filled、Outlined、Danger 或默认 Elevated 外观；Outline 为 Outlined 别名。与 Shape 独立。"
                : "Filled、Outlined、Danger 或 Elevated 外观；null 继承网格外观，独立使用时默认 Elevated。Outline 为 Outlined 别名。",
        "Variant" => "Filled、Outlined、Danger、Quiet、Underline 或 Elevated 外观；Disabled / Busy 是状态属性。",
        "OnSecondaryClick" => "激活次按钮时通知宿主，与主按钮动作独立。",
        "Selected" => "同时为主按钮和次按钮显示选中状态。",
        "Expanded" => "关联区域是否展开；由宿主更新，展开标记跟随此状态旋转。",
        "SecondaryControls" => "次按钮所控制区域的 HTML ID。",
        "SecondaryIcon" => "默认箭头使用共享 ExpansionIndicator；其他名称显示对应 Google 图标。",
        "PrimaryAttributes" or "SecondaryAttributes" => "主按钮或次按钮的原生 HTML 属性。",
        "PrimaryClass" or "SecondaryClass" => "主按钮或次按钮追加的 CSS 类。",
        "Type" when parameter.DeclaringType?.IsGenericType == true && parameter.DeclaringType.GetGenericTypeDefinition() == typeof(Controls.DateBox<>)
            => "InputDate 的日期或时间呈现类型；宿主绑定的 TValue 必须与所选类型相适应。",
        "Type" => "原生 button/input 类型，例如 submit、button、text、email。",
        "Busy" or "IsBusy" or "EditingBusy" => "宿主提供的处理中状态，限制重复操作或关闭。",
        "Disabled" => "使控件不可交互；真实权限仍由宿主检查。",
        "DisabledMessage" => "解释操作不可用的原因。",
        "Hidden" => "隐藏控件并按其生命周期释放活动交互。",
        "Title" when parameter.DeclaringType == typeof(Controls.UniformGridItem) || parameter.DeclaringType == typeof(Controls.UniformGridButton)
            => "格面标题，使用 H1 的 34px 字号；省略时不生成标题。",
        "Text" when parameter.DeclaringType == typeof(Controls.UniformGridItem) || parameter.DeclaringType == typeof(Controls.UniformGridButton)
            => "格面说明，使用正文 17px 字号；省略时不生成说明。",
        "Label" or "Title" or "Message" or "Description" or "Text" => "宿主提供的显示或播报文字。",
        "Placeholder" => "空输入提示，不能代替可访问标签。",
        "Id" or "ContentId" => "目标元素稳定且唯一的 HTML 标识。",
        "LabelledBy" => "已有标签元素 ID，用于 aria-labelledby。",
        "For" => "与模型字段关联的 lambda，用于获取验证消息。",
        "Required" => "必填显示与语义；模型校验规则由宿主配置。",
        "Error" => "真实错误文本或状态，不替换成空数据成功状态。",
        "FullWidth" => "占用整行或完整正文区域。",
        "Columns" when parameter.PropertyType == typeof(bool) => "启用事实内容的多栏布局。",
        "Columns" when parameter.PropertyType == typeof(int) => "常规布局列数，按该组件允许的范围配置。",
        "Columns" when parameter.PropertyType == typeof(int?) => "显式指定网格列数；省略时自动按可用宽度分配。",
        "Columns" when IsListView(parameter) => "复用 TableColumn<TItem> 的列顺序、标题、值选择和 Format；Sortable / Searchable / CanHide 元数据不启用动态操作。",
        "Columns" => "列元数据，定义标题、值选择、格式和可用操作。",
        "NarrowColumns" when parameter.DeclaringType == typeof(Controls.UniformGrid)
            => "在窄窗口显式覆盖列数；省略时继续使用自动分列或 Columns / Rows 配置。",
        "NarrowColumns" => "窄窗口列数；省略时继承 Columns。",
        "Filled" when parameter.DeclaringType == typeof(Controls.UniformGrid)
            => "兼容属性；true 将外观设为 Filled 并覆盖 Variant，false 保留 Variant。",
        "Filled" => "使用填充外观，不改变行列布局。",
        "Fluid" => "使用流动正文轨道；可空值继承应用布局配置。",
        "Compact" => "使用紧凑标题状态。",
        "FocusInvalidFields" => "验证失败后聚焦首个无效字段。",
        "Min" or "Max" or "Step" => "原生数值输入的范围或步长。",
        "MaxLength" or "MaximumLength" or "NewItemMaximumLength" => "输入或新建名称的最大长度。",
        "Multiline" => "使用 textarea 多行输入。",
        "Rows" when parameter.PropertyType == typeof(int) => "多行输入的可见行数。",
        "Rows" when parameter.PropertyType == typeof(int?) => "显式指定网格行数；只指定行数时按列填充。",
        "Rows" => "编辑网格行，单元格数量须与列数一致。",
        "Mask" => "输入掩码格式；仍需宿主业务校验。",
        "InputMode" => "原生输入键盘提示，例如 numeric。",
        "Options" => "可选择值、显示文字和禁用状态。",
        "Items" when IsListView(parameter) => "按传入顺序完整展示所有只读记录；无内置请求、过滤、排序或分页。",
        "Items" => "传入的数据集合；组件不会自动请求远程数据。",
        "ItemKey" when IsListView(parameter) => "宿主提供的稳定行键，仅供 Blazor 渲染识别记录，不增加选择或行操作。",
        "ValueSelector" or "KeySelector" or "ItemKey" => "获取值或稳定键的宿主函数。",
        "TextSelector" or "SearchTextSelector" => "获取显示或搜索文字的函数。",
        "SelectedId" => "当前单个引用值；null 表示没有选择。",
        "SelectedValues" => "宿主维护的已选择值集合。",
        "SelectionChanged" when IsGenericControl(parameter, typeof(Controls.Primitives.MultiSelectDropdown<,>))
            => "通知宿主切换单个 TValue；不是完整集合。宿主维护 SelectedValues，此回调不能用于 @bind-SelectedValues。创建期间不接受选择变更。",
        "SelectionChanged" when IsGenericControl(parameter, typeof(Controls.Primitives.ReferenceDropdown<>))
            => "通知宿主新的 nullable TValue 引用 ID；null 表示清除。宿主更新 SelectedId，此名称不是 @bind-SelectedId 的 Changed 配对。",
        "SelectionChanged" => "选择变化通知；按对应组件契约更新宿主状态。",
        "ItemSelected" => "候选项被选择时通知宿主。",
        "AllowNone" => "允许清除单选引用。",
        "CreateRequested" => "请求宿主创建选项，组件不保存远程对象。",
        "MaximumSelections" or "MaximumResults" => "限制选择数量或候选结果数量。",
        "FilterItems" when parameter.PropertyType == typeof(bool) => "启用控件内置的候选文字过滤；false 时由宿主提供已过滤的候选集合。",
        "FilterItems" => "候选过滤函数，支持宿主匹配逻辑。",
        "DebounceMilliseconds" => "搜索防抖延迟，单位毫秒。",
        "SearchRequested" => "可取消的异步搜索，接收查询文字和 CancellationToken。",
        "SearchChanged" when IsGenericControl(parameter, typeof(Controls.DataTable<>)) => "通知统一 TableSearchRequest，保留离页/草稿保护，不执行网络调用。",
        "SearchChanged" or "InputChanged" or "Changed" => "当前输入或查询条件变化通知。",
        "SearchCleared" => "搜索清空通知。",
        "OnSearch" => "应用搜索提交回调。",
        "ColumnKey" => "当前搜索列的稳定键。",
        "Searchable" or "ShowSearch" => "启用或显示搜索入口。",
        "View" => "当前表格或卡片视图。",
        "ViewChanged" => "视图切换通知。",
        "Loading" => "显示加载状态，不把未返回的数据当作空结果。",
        "LoadingMessage" or "EmptyMessage" or "EmptyText" or "EmptySelectionText" or "MultipleSelectionText" or "UnlistedName" => "对应加载、空结果或选择状态的说明。",
        "PageSize" => "每页显示的记录数；DataTable 默认 10，可由控制器切换。",
        "PageSizeChanged" => "每页数量变化通知；支持 @bind-PageSize。",
        "CurrentPage" => "当前页码，从 1 开始。",
        "TotalCount" => "当前数据范围内的真实总数。",
        "PageChanged" => "用户请求的新页码。",
        "IsLimited" or "HasMore" => "说明当前结果受限或有后续数据。",
        "ShowRange" => "显示当前页记录范围。",
        "PaginationResetKey" => "变化时重置分页的宿主标识。",
        "Culture" when IsListView(parameter) => "只读单元格格式化使用的 CultureInfo；省略时跟随当前作用域 ITextProvider.FormatCulture，显式值优先。",
        "Culture" => "比较和格式化使用的 CultureInfo。",
        "OnRowOpen" => "宿主明确提供的记录打开动作。",
        "RowOpenAvailable" => "显式 OnRowOpen 的逐行可用条件；菜单打开项、行交互标记和回调均检查此条件，不代替服务端授权。",
        "RowActionsContent" => "标准 ActionMenu 中的完整原生行操作内容，列表与卡片共用；与非空 Actions 互斥，不再自动插入 Open。原生 GET/POST、target 等由宿主保留。双击须同时声明 OnRowOpen/RowOpenAvailable 和唯一 data-record-open A/Form；POST 要求唯一可用 submitter，缺失/歧义/禁用时拒绝激活。",
        "RowHeaderKey" => "指定已有列键，将该列单元格呈现为 th scope=row 的行标题；null 使用普通数据单元格。",
        "Caption" when IsListView(parameter) => "辅助技术可读的表格说明；默认 null 使用 Label，说明在视觉上隐藏。",
        "CellTemplate" when IsListView(parameter) => "只读单元格模板；TableCellContext<TItem> 提供原始 Item、共享 Column 和已格式化 Text。默认文本自动转义；自定义模板负责其内容与可访问语义。",
        "CellTemplate" when parameter.DeclaringType == typeof(Controls.Primitives.EditingGrid) => "只用于 GridEditorKind.Template 的编辑器内容；GridCellContext 提供行/列/单元格和合成后的禁用状态。仍处于同一键盘/剪贴板单元格，宿主保留编辑事务与值，不能绕过 ReadOnly/Disabled。",
        "CellTemplate" or "BulkEditCell" => "单元格显示或批量编辑模板。",
        "Progressive" => "无交互连接的标准表格渐进增强：全量授权可见文本 SSR 和原生动作，库内控制器搜索/排序/分页/列显隐/视图。拒绝隐藏默认列、独立搜索/排序值和编辑；不序列化额外记录字段。",
        "NativeRowOpen" => "明确通过 RowActionsContent 中唯一的 data-record-open 原生动作打开记录；必须有该插槽，不得同时提供虚假回调或 RowOpenHref。",
        "RowOpenHref" => "按记录提供真实 GET 链接；与 OnRowOpen 互斥。自定义完整 RowActionsContent 时由宿主放入唯一标准打开动作，库不追加重复操作。",
        "SearchMode" => "Local 使用共享 TableData 算法；Remote 只通知宿主请求，不对服务端结果再次过滤。远端搜索仅选择实际可搜索列。",
        "SearchQuery" or "SearchColumnKey" => "远端搜索的受控查询值与稳定列键；业务取消、去抖和授权属于宿主。",
        "SearchContent" => "标准搜索行内的筛选内容插槽，与 DataSearch.ChildContent 复用布局；放入实际 Flourish 控件。",
        "SearchDisabled" => "禁用查询输入而不隐藏结果；编辑忙碌状态同样阻止查询。",
        "SearchId" => "统一搜索输入的稳定标识，与 Field 标签关联。",
        "SearchMaximumLength" => "查询文字最大长度；标准搜索控件同时处理原生限制和回调限制。",
        "ShowRowActions" => "显示记录操作能力；批量编辑或业务不可用时保持打开行为关闭。",
        "PreferenceKey" when IsGenericControl(parameter, typeof(Controls.DataTable<>)) => "可选稳定、非翻译排序偏好隔离键；复用当前 scoped ITablePreferences，省略保留组件内状态，不承诺跨窗口或持久化。",
        "PreferenceKey" => "表格偏好的隔离键。",
        "Purpose" => "表格的登记、数据池或任务列表用途。",
        "CellChanged" => "单元格提出变更时通知宿主；校验和保存仍由宿主处理。",
        "Interactions" => "撤销、重做、保存、粘贴及错误报告回调集合。",
        "MeasurementRevision" => "显示数据变化后的测量版本。",
        "EditDisabled" => "阻止编辑但保留可读内容。",
        "BulkEditing" => "正在进行批量编辑的状态。",
        "BulkEditRequested" => "进入批量编辑的请求。",
        "IsSelectedForEditing" or "AllEditSelected" => "行或全体编辑选择状态。",
        "ToggleEditSelection" or "ToggleAllEditSelection" => "切换行或全体编辑选择的回调。",
        "ShowActions" => "显示记录操作区域。",
        "DefaultAction" or "DefaultActionContent" or "DefaultActionHref" or "DefaultActionAvailable" => "默认操作、内容、目标或可用条件。",
        "SpreadsheetEditHref" => "表格式编辑导航地址。",
        "IsOpen" => "弹层打开状态，按关闭回调同步宿主状态。",
        "IsOpenChanged" => "打开状态通知，用于 @bind-IsOpen。",
        "OnClose" => "请求宿主关闭，由宿主更新 IsOpen。",
        "CanClose" => "关闭前异步许可，可保护未保存内容。",
        "Presentation" => "居中或底部面板呈现。",
        "TriggerContent" => "菜单触发器的 Razor 内容。",
        "Severity" => "严重程度，决定外观与默认播报语义。",
        "Subtle" => "轻量通知外观。",
        "Announce" => "启用辅助技术播报。",
        "Role" => "原生辅助技术角色，须符合实际语义。",
        "StatusText" => "任务当前阶段，不虚构进度。",
        "Stopped" => "暂停进度环旋转。",
        "InitiallyOpen" => "原生展开区域初始状态。",
        "Href" or "HomeHref" or "ParentHref" or "IdentityHref" => "宿主定义的导航地址。",
        "ParentLabel" => "真实上级页面链接文字。",
        "BrandName" when parameter.DeclaringType == typeof(Controls.PresentationFooter)
            => "显式覆盖项目品牌的兼容参数；通常省略，标题与默认水印自动读取 ConfigureProject.SetProjectName(string/TextReference)。版权仍由宿主独立提供。",
        "IdentityName" or "BrandName" or "ApplicationTitle" => "身份、品牌或应用显示名。",
        "LogoPath" => "宿主提供的标志图片路径。",
        "Match" => "NavLink 精确或前缀匹配方式。",
        "IsCurrent" => "当前导航项状态。",
        "PrimaryNavigation" or "SecondaryNavigation" or "NavigationGroups" => "宿主导航内容或元数据。",
        "ShowSecondary" => "显示二级导航。",
        "DocumentKey" => "正文身份，变化时重置内容滚动。",
        "Facts" or "SideFacts" => "身份事实条目，包含主值和标识符标记。",
        "SideContent" => "身份卡片侧栏插槽。",
        "Contents" => "指向实际区块的页内目录。",
        "ShowContents" => "显示页内目录。",
        "Form" => "按钮关联的 form 元素 ID。",
        "HasUnsavedChanges" => "导航保护使用的未保存状态。",
        "Locked" => "暂时限制被包裹内容的交互。",
        "Emphasized" => "强调显示方式。",
        "Prominent" => "大展示卡片模式，左侧标准操作、右侧 H1 字号正文；不是业务普通 Card 的默认呈现，false 保留原 Title / ChildContent 结构。",
        "Language" => "代码语言标签；不执行显示文本。",
        "Status" or "TitleBar" or "TitleBarStart" or "TitleBarBrand" or "TitleBarEnd" or "LeadingActions" or "EndActions" or "Services" => "该命名区域的 Razor 插槽。",
        _ when parameter.Name.EndsWith("Label", StringComparison.Ordinal) => "对应操作或区域的显示/可访问说明。",
        _ when typeof(RenderFragment).IsAssignableFrom(parameter.PropertyType) => "宿主提供的 Razor 内容插槽。",
        _ => "宿主配置；具体组合见完整场景源码与变体说明。"
    };

    private static bool IsListView(PropertyInfo parameter) => parameter.DeclaringType?.IsGenericType == true
        && parameter.DeclaringType.GetGenericTypeDefinition() == typeof(Controls.ListView<>);
    private static bool IsGenericControl(PropertyInfo parameter, Type definition) => parameter.DeclaringType?.IsGenericType == true
        && parameter.DeclaringType.GetGenericTypeDefinition() == definition;
}
