<Project>
  <PropertyGroup>
    <VersionPrefix>1.4.0</VersionPrefix>
    <Authors>ArkheideSystem</Authors>
    <Company>ArkheideSystem</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Evigila/Flourish</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Evigila/Flourish.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageOutputPath>$(MSBuildThisFileDirectory)artifacts/packages</PackageOutputPath>
    <Deterministic>true</Deterministic>
    <EssentialCultureVersion>1.4.0</EssentialCultureVersion>
  </PropertyGroup>
</Project>
