<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>Flourish.WPF.Test</AssemblyName>
    <RootNamespace>ArkheideSystem.Flourish.WPF.Test</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x86;x64;ARM64</Platforms>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RunSettingsFilePath>$(MSBuildThisFileDirectory)coverage.runsettings</RunSettingsFilePath>
    <EssentialCultureGeneratorEnabled>false</EssentialCultureGeneratorEnabled>
    <EssentialCultureAutoCreate>false</EssentialCultureAutoCreate>
    <EssentialCultureAutoInclude>false</EssentialCultureAutoInclude>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Flourish.WPF\Flourish.WPF.csproj" />
    <ProjectReference Include="..\..\src\Gallery.WPF\Gallery.WPF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\src\Gallery.WPF\Localization\Culture.json"
          Link="Culture.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
