<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ArkheideSystem.Tests.Flourish.WPF</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EssentialCultureGeneratorEnabled>false</EssentialCultureGeneratorEnabled>
    <EssentialCultureAutoCreate>false</EssentialCultureAutoCreate>
    <EssentialCultureAutoInclude>false</EssentialCultureAutoInclude>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" PrivateAssets="all" />
    <ProjectReference Include="../../src/Flourish.WPF/Flourish.WPF.Abstract/Flourish.WPF.Abstract.csproj" />
    <ProjectReference Include="../../src/Flourish.WPF/Flourish.WPF.Framework/Flourish.WPF.Framework.csproj" />
    <ProjectReference Include="../../src/Flourish.WPF/Flourish.WPF.Design/Flourish.WPF.Design.csproj" />
    <ProjectReference Include="../../src/Gallery.Flourish.WPF/Gallery.Flourish.WPF.csproj" />
  </ItemGroup>
</Project>
