<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Gallery.Flourish.Blazor</AssemblyName>
    <RootNamespace>ArkheideSystem.Gallery.Flourish.Blazor</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>

    <EssentialCultureNamespace>ArkheideSystem.Gallery.Flourish.Blazor.Texts</EssentialCultureNamespace>
    <EssentialCultureGeneratorEnabled>true</EssentialCultureGeneratorEnabled>
    <EssentialCultureXamlFramework>none</EssentialCultureXamlFramework>
    <EssentialCultureAutoInclude>false</EssentialCultureAutoInclude>
    <EssentialCultureAutoCreate>false</EssentialCultureAutoCreate>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Localization/Culture.json" />
    <Content Remove="Localization/Culture.json" />
    <AdditionalFiles Include="Localization/Culture.json" />
    <EmbeddedResource Include="Localization/Culture.json" LogicalName="Gallery.Texts.json" />
    <CompilerVisibleProperty Include="EssentialCultureNamespace" />
    <CompilerVisibleProperty Include="EssentialCultureGeneratorEnabled" />
    <CompilerVisibleProperty Include="EssentialCultureXamlFramework" />
    <EmbeddedResource Include="Components/Samples/**/*.razor" />
    <ProjectReference Include="../Flourish.Blazor/Flourish.Blazor.Framework/Flourish.Blazor.Framework.csproj" />
    <ProjectReference Include="../Flourish.Blazor/Flourish.Blazor.Design/Flourish.Blazor.Design.csproj" />
    <PackageReference Include="Arkheide.Flourish.Extensions.Culture.Blazor" Version="$(VersionPrefix)" />
  </ItemGroup>
</Project>
