<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ArkheideSystem.Flourish.Extension.Culture</RootNamespace>
    <AssemblyName>Arkheide.Flourish.Extension.Culture</AssemblyName>
    <PackageId>Arkheide.Flourish.Extension.Culture</PackageId>
    <Title>Arkheide.Flourish.Extension.Culture</Title>
    <Authors>Arkheide</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/Evigila/Flourish</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Evigila/Flourish.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Description>Connects Arkheide.Flourish with Arkheide.Essential.Culture.</Description>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x86;x64;ARM64</Platforms>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ArkheideEssentialCultureGeneratorEnabled>false</ArkheideEssentialCultureGeneratorEnabled>
    <ArkheideEssentialCultureAutoCreate>false</ArkheideEssentialCultureAutoCreate>
    <ArkheideEssentialCultureAutoInclude>false</ArkheideEssentialCultureAutoInclude>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flourish\Arkheide.Flourish.csproj" />
    <PackageReference Include="Arkheide.Essential.Culture.Wpf" Version="$(ArkheideEssentialCultureVersion)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
