<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>Tests.Flourish.Extensions.Culture.WPF</AssemblyName>
    <RootNamespace>ArkheideSystem.Tests.Flourish.Extensions.Culture.WPF</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x86;x64;ARM64</Platforms>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EssentialCultureNamespace>ArkheideSystem.Tests.Flourish.Extensions.Culture.WPF.Texts</EssentialCultureNamespace>
    <EssentialCultureGeneratorEnabled>true</EssentialCultureGeneratorEnabled>
    <EssentialCultureAutoCreate>false</EssentialCultureAutoCreate>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="../../src/Flourish.Extensions/Flourish.Extensions.Culture.WPF/Flourish.Extensions.Culture.WPF.csproj" />
  </ItemGroup>
  <ItemGroup>
    <CultureModule Include="Culture.Records.json" ModuleId="Records" DeploymentPath="Records/Culture.Records.json" />
  </ItemGroup>
</Project>
