<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>Gallery.Flourish.WPF</AssemblyName>
    <RootNamespace>ArkheideSystem.Gallery.Flourish.WPF</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <StartupObject>ArkheideSystem.Gallery.Flourish.WPF.Program</StartupObject>
    <Platforms>AnyCPU;x86;x64;ARM64</Platforms>
    <UserSecretsId>Gallery.WPF</UserSecretsId>
    <ShouldUnsetParentConfigurationAndPlatform>false</ShouldUnsetParentConfigurationAndPlatform>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Arkheide.Essential.Culture.Wpf" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flourish.WPF\Flourish.WPF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Localization\Culture.json" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Localization\Culture.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Culture.json</TargetPath>
    </None>
    <None Update="FlourishCulture.Json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
