<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Gallery.Flourish.WPF</AssemblyName>
    <RootNamespace>ArkheideSystem.Gallery.Flourish.WPF</RootNamespace>
    <IsPackable>false</IsPackable>
    <EssentialCultureGeneratorEnabled>false</EssentialCultureGeneratorEnabled>
    <EssentialCultureAutoCreate>false</EssentialCultureAutoCreate>
    <EssentialCultureAutoInclude>false</EssentialCultureAutoInclude>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Flourish.WPF/Flourish.WPF/Flourish.WPF.csproj" />
    <ProjectReference Include="../Flourish.Extensions/Flourish.Extensions.Culture.WPF/Flourish.Extensions.Culture.WPF.csproj" />
    <None Update="Culture.json" CopyToOutputDirectory="PreserveNewest" />
    <Resource Include="../Gallery.Flourish.Blazor/wwwroot/gallery.svg" Link="Artwork/gallery.svg" />
  </ItemGroup>
</Project>
