apiRules:
- include:
    uidRegex: ^ArkheideSystem\.Flourish\.Abstract
- include:
    uidRegex: ^ArkheideSystem\.Flourish\.Controls
- include:
    uidRegex: ^ArkheideSystem\.Flourish\.Styles
- include:
    uidRegex: ^ArkheideSystem\.Flourish\.Themes
- exclude:
    uidRegex: ^ArkheideSystem\.Flourish\.
